# Form implementation generated from reading ui file 'movie3.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Movie3(object):
    def setupUi(self, Movie3):
        Movie3.setObjectName("Movie3")
        Movie3.resize(393, 377)
        self.centralwidget = QtWidgets.QWidget(parent=Movie3)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 40, 351, 281))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(150, 10, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 151, 16))
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBox.setGeometry(QtCore.QRect(20, 100, 201, 20))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(120, 210, 121, 24))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 49, 16))
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 391, 31))
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 0, 75, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        Movie3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Movie3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 393, 22))
        self.menubar.setObjectName("menubar")
        Movie3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Movie3)
        self.statusbar.setObjectName("statusbar")
        Movie3.setStatusBar(self.statusbar)

        self.retranslateUi(Movie3)
        QtCore.QMetaObject.connectSlotsByName(Movie3)

    def retranslateUi(self, Movie3):
        _translate = QtCore.QCoreApplication.translate
        Movie3.setWindowTitle(_translate("Movie3", "MainWindow"))
        self.label.setText(_translate("Movie3", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:700;\">MOVIE 3</span></p></body></html>"))
        self.label_2.setText(_translate("Movie3", "<html><head/><body><p><span style=\" font-weight:700;\">Showing Schedule:</span></p></body></html>"))
        self.checkBox.setText(_translate("Movie3", "   03:00:00 - 06:00:00   05/20/2025"))
        self.pushButton.setText(_translate("Movie3", "SELECT YOUR SEAT"))
        self.label_3.setText(_translate("Movie3", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">₱300.00</span></p></body></html>"))
        self.pushButton_6.setText(_translate("Movie3", "Back"))
